version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: postgres
    environment:
      - POSTGRES_USER=short
      - POSTGRES_PASSWORD=UrlSh0rtn3r
      - POSTGRES_DB=url_shortner
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    image: postgres:latest
    ports:
      - 5432:5432
  api:
    container_name: shortUrl-web
    environment:
      - FLASK_HOST=127.0.0.1
      - FLASK_PORT=5000
      - FLASK_APP=api
      - FLASK_ENV=development
    build:
      context: .
      dockerfile: api.docker
    ports:
      - 5000:5000
    links:
      - db