# build from project root 'docker build -t shortner -f ops\Dockerfile.flask .'
# run from project root 'docker run shortner'
FROM python:3.8-slim-buster

WORKDIR ../app
COPY ../requirements.txt requirements.txt

RUN python -m pip install --upgrade pip
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
RUN pip3 install -r requirements.txt
COPY . .
CMD [ "flask", "run" ]