version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    container_name: shortUrl-web
    environment:
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    build:
      context: ..
      network: host
      dockerfile: ops\Dockerfile.flask
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    links:
      - "db:${POSTGRES_HOST}"