version: "3.9"  # optional since v1.27.0
services:
  db:
    environment:
      POSTGRES_PASSWORD: UrlSh0rtn3r
      POSTGRES_DB: url_shortner
      POSTGRES_PORT: 5432
    image: postgres:latest
    networks:
      - flasknetwork
  api:
    container_name: shortUrl-web
    restart: on-failure
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 8000
      FLASK_APP: shortner
      FLASK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: UrlSh0rtn3r
      POSTGRES_DB: url_shortner
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ../app:/app
    build:
      context: ..
      dockerfile: ops/Dockerfile.flask
    ports:
      - "8000:8000"
    networks:
      - flasknetwork
    depends_on:
      - db
networks:
  flasknetwork:
      driver: bridge
